version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app-deployment

hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: ec2-user
      
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user
      
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: ec2-user